# Generated by Django 4.0.3 on 2022-03-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='bookSummary',
            field=models.TextField(max_length=150),
        ),
    ]
