# Generated by Django 4.0.3 on 2022-03-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0002_alter_books_booksummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
